stages:
  - publish

build-helm-chart:
  image: alpine/helm:3
  stage: publish
  script:
    - helm package ./momo-store-chart
    - cd /builds/std-ext-006-10/argocd-app/
    - curl -u ${NEXUS_REPO_USER}:${NEXUS_REPO_PASS} https://nexus.praktikum-services.tech/repository/momo-store-std-ext-006-10/ --upload-file momo-store-chart-0.1.0.tgz
